const categories=[['👋','Greetings'],['❤️','Love Language'],['☕','At the Café'],['🛒','At the Supermarket'],['🎉','At a Family Event'],['🏠','With Family'],['👭','With Friends'],['🎓','Teacher & Classmates'],['🔢','Numbers'],['🧍','Body Parts'],['🧭','Directions'],['📅','Months'],['💶','Money'],['🗓️','Dates'],['🛡️','Bullies & Insults'],['🔥','Flirting & Sexy Talk'],['🍽️','Food']];
const seed={
'Greetings':[['Salut ! Comment ça va ?','Sa-lu! Ko-moñ sa-va?','Hi! How are you?'],['Ça fait plaisir de te revoir.','Sa-fe-ple-zir deu-te-re-vwar.','It’s great to see you again.'],['Comment vas-tu depuis ?','Ko-moñ va-tu de-pwi?','How have you been?']],
'Love Language':[['Je t’aime, mon cher Dimitri.','Je-tem, moñ-sher Di-mi-tri.','I love you, my dear Dimitri.'],['Tu m’as manqué.','Tu-ma mã-ke.','I missed you.']],
'At the Café':[["Un café, s’il vous plaît.",'Eñ ka-fe, sil-vu-ple.','A coffee, please.']],
'At the Supermarket':[['Ça coûte combien ?','Sa-kut koḿ-byeñ?','How much does this cost?']],
'At a Family Event':[["Je suis contente d’être ici.",'Je-swi kon-tant detr i-si.','I’m happy to be here.']],
'With Family':[['Tu as faim ?','Tu-a-faḿ?','Are you hungry?'],["J’ai faim.",'Je-faḿ.','I’m hungry.']],
'With Friends':[['On y va !','Oñ-ni-va!','Let’s go!']],
'Teacher & Classmates':[['Je ne comprends pas.','Je-neu-koḿ-prã-pa.','I don’t understand.']],
'Bullies & Insults':[['Tu te moques de moi ?','Tu-teu-mok deu-mwa?','Are you making fun of me?'],['Laisse-moi tranquille.','Les-mwa trã-kil.','Leave me alone.']],
'Flirting & Sexy Talk':[['Tu es sexy.','Tu-e-sek-si.','You’re sexy.'],['Embrasse-moi.','Ã-bras-mwa.','Kiss me.']],
'Food':[["J’ai sommeil.",'Je-so-mey.','I’m sleepy.'],["C’est délicieux.",'Se de-li-syeu.','It’s delicious.']],
'Numbers':[['un, deux, trois','eñ, deu, trwa','one, two, three']],
'Body Parts':[['la tête','la-tet','the head'],['la main','la-meñ','the hand']],
'Directions':[['à gauche','a-gosh','to the left'],['à droite','a-drwat','to the right']],
'Months':[['janvier','jã-vye','January'],['février','fe-vri-ye','February']],
'Money':[['dix euros','dis-eu-ro','ten euros']],
'Dates':[['Quelle est la date ?','Kel-e-la-dat?','What is the date?']]
};
let state={tense:localStorage.tense||'Present',order:localStorage.order||'Sequential',known:JSON.parse(localStorage.known||'{}')};
const app=document.querySelector('#app');
function save(){localStorage.tense=state.tense;localStorage.order=state.order;localStorage.known=JSON.stringify(state.known)}
function speak(t,lang='fr-FR'){speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang=lang;u.rate=.8;speechSynthesis.speak(u)}
function home(){app.innerHTML=`<main class=shell><div class=top><div><div class=brand>Bonjour 👋</div><div class=sub>French that a Filipino can actually practice.</div></div><button onclick="sounds()">👄 Sounds</button></div><section class=panel><b>Choose tense</b><div class=row style='margin-top:10px'>${['Present','Past','Future','Mixed'].map(x=>`<button class='${state.tense==x?'active':''}' onclick="state.tense='${x}';save();home()">${x}</button>`).join('')}</div><div class=small style='margin-top:9px'>Mixed combines tenses once you want harder recall.</div></section><section class=panel><b>Learning order</b><div class=row style='margin-top:10px'>${['Sequential','Random'].map(x=>`<button class='${state.order==x?'active':''}' onclick="state.order='${x}';save();home()">${x}</button>`).join('')}</div></section><h2>Categories</h2><div class=grid>${categories.map(c=>`<div class=tile onclick='study(${JSON.stringify(c[1])})'><span class=emoji>${c[0]}</span><b>${c[1]}</b><span class=small>${(seed[c[1]]||[]).length} starter cards</span></div>`).join('')}</div></main>`}
function study(cat){let cards=[...(seed[cat]||[])];if(state.order==='Random')cards.sort(()=>Math.random()-.5);let i=0;render();function render(){let c=cards[i];if(!c){app.innerHTML=`<main class=shell><button class=back onclick=home()>← Home</button><div class=panel><h2>${cat}</h2><p>Starter cards for this category are being expanded. The app structure is ready.</p></div></main>`;return}let key=cat+'|'+c[0];app.innerHTML=`<main class=shell><button class=back onclick=home()>← Categories</button><div class=top><h2>${cat}</h2><span>${i+1}/${cards.length}</span></div><div class=progress><i style='width:${(i+1)/cards.length*100}%'></i></div><article class=card><div class=label>🇫🇷 French</div><div class=fr>${c[0]}</div><button onclick='speak(${JSON.stringify(c[0])})'>🔊 French audio</button><div class=label>🗣️ Filipinized pronunciation</div><div class=ph>${c[1]}</div><button onclick='speak(${JSON.stringify(c[1])},"fil-PH")'>🔊 Filipinized audio</button><div class=label>🇬🇧 English</div><div class=en>${c[2]}</div></article><div class=nav><button onclick='mark(false)'>× Practice again</button><button class=primary onclick='mark(true)'>✓ I know this</button></div></main>`;window.mark=(v)=>{state.known[key]=v;save();i=(i+1)%cards.length;render()}}}
function sounds(){let groups=[['E family','é / er / ez','café','ka-fe','Je bois un café.','Je-bwa eñ ka-fe.','I drink a coffee.'],['OI','oi','moi','mwa','Regarde-moi.','Re-gard-mwa.','Look at me.'],['OU','ou','vous','vu','Comment allez-vous ?','Ko-moñ ta-le-vu?','How are you?'],['CH','ch','chat','sha','Le chat dort.','Leu-sha dor.','The cat sleeps.'],['GN','gn','montagne','moñ-tañ','La montagne est belle.','La-moñ-tañ e-bel.','The mountain is beautiful.']];if(state.order==='Random')groups.sort(()=>Math.random()-.5);app.innerHTML=`<main class=shell><button class=back onclick=home()>← Home</button><h1>👄 French Sounds Lab</h1><p class=sub>Study sound families in ${state.order.toLowerCase()} order.</p>${groups.map(g=>`<div class=soundBox><b>${g[0]}</b><div class=small>Spelling: ${g[1]}</div><h3>${g[2]} → ${g[3]}</h3><button onclick='speak(${JSON.stringify(g[2])})'>🔊 Hear French</button><div class=label>Sample sentence</div><div class=fr style='font-size:20px'>${g[4]}</div><div class=ph style='font-size:18px'>${g[5]}</div><div>${g[6]}</div></div>`).join('')}</main>`}
window.home=home;window.study=study;window.sounds=sounds;window.speak=speak;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');home();
